export enum RequestRoutes {
  SCRIPTS = "SCRIPTS",
  SCRIPT_URL = "SCRIPT_URL",
  CUSTOM_RECORDS = "CUSTOM_RECORDS",
  CUSTOM_RECORD_URL = "CUSTOM_RECORD_URL",
  RUN_QUICK_SCRIPT = "RUN_QUICK_SCRIPT",
  SCRIPTS_DEPLOYED = "SCRIPTS_DEPLOYED",
  CURRENT_REC_TYPE = "CURRENT_REC_TYPE",
  EXPORT_RECORD = "EXPORT_RECORD",
}
