/**
 * AI documentation for the diagram DSL.
 * Appended to the system prompt so the AI knows how to generate diagrams.
 */

/* eslint-disable no-useless-escape */

export const DIAGRAM_DOCS = [
  "",
  "## Diagrams \u2014 Visual Flowcharts & Sequences",
  "Embed visual diagrams using a \\`diagram\\` code fence. The renderer produces clean SVG inline in the chat.",
  "",
  "### Flowchart",
  "First line: \\`flowchart TD\\` (top-down) | \\`flowchart LR\\` (left-right) | \\`flowchart BT\\` | \\`flowchart RL\\`",
  "",
  "\\`\\`\\`diagram",
  "flowchart TD",
  "  A(Start) --> B[Check Record]",
  "  B --> C{Valid?}",
  "  C -->|Yes| D[(Save Record)]",
  "  C -->|No| E[Log Error]",
  "  D --> F(End)",
  "  E --> F",
  "\\`\\`\\`",
  "",
  "#### Node shapes \u2014 follow these rules exactly",
  "| Syntax | Shape | When to use |",
  "|--------|-------|-------------|",
  "| \\`[text]\\` | Rectangle | **Default for all process steps** |",
  "| \\`(text)\\` | Rounded rect | Start / End terminals |",
  "| \\`{Short label}\\` | Diamond | Decisions \u2014 label MUST be \u22645 words |",
  "| \\`[(text)]\\` | Cylinder | NetSuite records, databases |",
  "| \\`((X))\\` | Circle | ONLY for 1-2 word labels: Start, End, Trigger |",
  "| \\`{{text}}\\` | Hexagon | External APIs, integrations |",
  "",
  "CRITICAL shape rules:",
  "- Diamond \\`{...}\\` labels MUST be \u22645 words. Bad: \\`{Is the data sufficient for enrichment?}\\`",
  "  Good: \\`{Data sufficient?}\\`  The diamond auto-sizes to label width \u2014 long labels create huge shapes.",
  "- Circle \\`((text))\\` is ONLY for very short labels (Start, End, Trigger, 1-2 words).",
  "  For any longer label use \\`[text]\\` or \\`(text)\\` instead. A circle with long text becomes enormous.",
  "- When in doubt: use \\`[text]\\` (rectangle).",
  "",
  "#### Edge styles",
  "  --> solid arrow   .-> dashed arrow   ==> thick arrow   -->|label| labeled arrow   --- line (no arrow)",
  "",
  "#### Subgraphs",
  "\\`\\`\\`diagram",
  "flowchart TD",
  "  A[Step 1] --> B[Step 2]",
  "  subgraph phase1 [\"Phase 1\"]",
  "    A",
  "    B",
  "  end",
  "\\`\\`\\`",
  "",
  "### Sequence diagram",
  "\\`\\`\\`diagram",
  "sequence",
  "  participant CS as Client Script",
  "  participant SL as Suitelet",
  "  participant API as N/record",
  "  CS ->> SL: POST request",
  "  SL ->> API: record.load()",
  "  API -->> SL: Record object",
  "  SL -->> CS: JSON response",
  "  note over SL,API: Server-side execution",
  "\\`\\`\\`",
  "",
  "#### Sequence arrows: ->> solid | -->> dashed (response) | -> simple | --> simple dashed",
  "",
  "### Quality guidelines \u2014 ALWAYS follow these",
  "1. Be COMPREHENSIVE: show ALL important steps. Don\u2019t skip validation, error handling, or intermediate steps.",
  "2. Every diamond MUST have labeled edges for both branches: -->|Yes| and -->|No| (or -->|Pass| / -->|Fail|).",
  "3. Show error/failure paths: what happens when something goes wrong (log, skip, retry, notify, throw).",
  "4. Ideal size: 8\u201315 nodes. For larger flows, use subgraphs to group phases.",
  "5. Keep ALL labels short (4-5 words max). Put details in the surrounding text, not the diagram.",
  "6. Every flow must have clear terminal nodes (End, Complete, Error state).",
  "7. Use meaningful node IDs for readable DSL code (e.g. loadRec, checkValid, saveDB).",
  "",
  "### NetSuite patterns",
  "- SuiteScript flows: show all relevant events (beforeLoad, beforeSubmit, afterSubmit)",
  "- Map/Reduce: show getInputData \u2192 map \u2192 reduce \u2192 summarize stages",
  "- Approval workflows: show each approval state and transition conditions",
  "- API/Integration: prefer sequence diagrams for multi-party request/response flows",
  "",
].join("\n");
